blueprint:
  name: Open/Close notifier
  description: Notify if a door was opened or closed
  domain: automation
  input:
    
    trigger_device:
      name: Door
      description: The triggering binary sensor
      selector:
        entity:
          domain: binary_sensor
          device_class: opening

mode: single

variables:
  trigger_device: !input 'trigger_device'

trigger:
  platform: state
  entity_id: !input 'trigger_device'

action:

  - alias: "Debug notify"
    service: notify.slack_debug
    data:
      message: > 
        {{ trigger.to_state.attributes.friendly_name }} was
        {% if trigger.to_state.state == "off" %}closed{% elif trigger.to_state.state == "on" %}opened{% endif %}
      title: "Door alert"

  - alias: "Notify Push"
    service: notify.pushover
    data:
      message: > 
        {{ trigger.to_state.attributes.friendly_name }} was
        {% if trigger.to_state.state == "off" %}closed{% elif trigger.to_state.state == "on" %}opened{% endif %}
      title: "Door alert"