blueprint:
  name: Open/Close notifier
  description: Notify if a door was opened or closed
  domain: automation
  input:
    
    trigger_device:
      name: Door
      description: The triggering binary sensor
      selector:
        entity:
          domain: binary_sensor
          device_class: opening

    actions:
      name: Actions
      description: >
        Run notifications or similar actions.
        Use something like 
        {{ trigger.to_state.attributes.friendly_name }} was {% if trigger.to_state.state == "off" %}closed{% elif trigger.to_state.state == "on" %}opened{% endif %}
      selector:
        action: {}

mode: single

variables:
  trigger_device: !input 'trigger_device'

trigger:
  platform: state
  entity_id: !input 'trigger_device'

action:
  - choose: []
    default: !input 'actions'